<a href="https://colab.research.google.com/github/Hongquanthaort/Git/blob/main/B%C3%A0i_t%E1%BA%ADp_v%E1%BB%81_nh%C3%A0_2_Vector_Ma_tr%E1%BA%ADn_Tensor_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy as np
from matplotlib import pyplot as plt

**Các phép toán với vector**

In [ ]:
x = np.array([1,2,3,4]) 
y = np.array([5,3,2,1]) 
z = x + y 
print(z) 
print(z.ndim) 
print(z.shape)

[6 5 5 5]
1
(4,)


In [ ]:
x = np.array([1,2,3,4]) 
a = 15 
z = a*x 
print(z) 
print(z.ndim) 
print(z.shape)

[15 30 45 60]
1
(4,)


In [ ]:
x = np.array([1,2,3,4]) 
y = np.array([5,3,2,1]) 
z = np.dot(x,y) #hoặc z = x.dot(y) 
print(z) 
print(z.ndim) 
print(z.shape)

21
0
()


In [ ]:
x = np.array([1,2,3]) 
y = np.array([3,2,1]) 
z = np.cross(x, y) 
print(z) 
print(z.ndim) 
print(z.shape)

[-4  8 -4]
1
(3,)


In [ ]:
x = np.array([1,2,3,4]) 
y = np.array([5,3,2,1]) 
z = x*y #hoặc z = np.multiply(x, y) 
print(z) 
print(z.ndim) 
print(z.shape)

[5 6 6 4]
1
(4,)


**Các phép toán với ma trận**

In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
Y = np.array([6,5,4,3,2,1]).reshape((2,3)) 
Z = X + Y 
print(Z) 
print(Z.ndim, '; ', Z.shape)

[[7 7 7]
 [7 7 7]]
2 ;  (2, 3)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
a = 2 
Z = a*X 
print(Z) 
print(Z.ndim, '; ', Z.shape)

[[ 2  4  6]
 [ 8 10 12]]
2 ;  (2, 3)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
Z = X.T 
print(Z) 
print(Z.ndim, '; ', Z.shape)

[[1 4]
 [2 5]
 [3 6]]
2 ;  (3, 2)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
Y = np.array([6,5,4,3,2,1]).reshape((3,2)) 
Z = np.dot(X,Y) 
print(Z) 
print(Z.ndim, '; ', Z.shape)

[[20 14]
 [56 41]]
2 ;  (2, 2)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
Y = np.array([6,5,4,3,2,1]).reshape((2,3)) 
Z = np.multiply(X,Y) #hoặc Z = X*Y 
print(Z) 
print(Z.ndim, '; ', Z.shape)

[[ 6 10 12]
 [12 10  6]]
2 ;  (2, 3)


In [ ]:
x = np.array([1,2,3,4,5]).reshape((5,1)) 
print(x) 
print(x.ndim, '; ', x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
2 ;  (5, 1)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
m = X.shape[0] 
n = X.shape[1] 
print('m = ', m, '; n = ', n) 
x = X[0, :] 
print(x) 
print(x.ndim, '; ', x.shape) 
x = x.reshape((1,n)) 
print(x) 
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[1 2 3]
1 ;  (3,)
[[1 2 3]]
2 ;  (1, 3)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3)) 
m = X.shape[0] 
n = X.shape[1] 
print('m = ', m, '; n = ', n) 
x = X[:,1] 
print(x) 
print(x.ndim, '; ', x.shape) 
x = x.reshape((m,1)) 
print(x) 
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[2 5]
1 ;  (2,)
[[2]
 [5]]
2 ;  (2, 1)


In [ ]:
X =  np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((4,3)) 
x = np.array([1,1,1,1]).reshape((4,1)) 
X = np.column_stack([x,X]) 
print(X) 
print(X.ndim, '; ', X.shape)

[[ 1  1  2  3]
 [ 1  4  5  6]
 [ 1  7  8  9]
 [ 1 10 11 12]]
2 ;  (4, 4)


In [ ]:
data = np.array([[10,22,13,1], 
    [9,6,5,0], 
    [8,12,4,1], 
    [6,5,7,0]]) 
X = data[:,:-1] 
y = data[:,-1].reshape((data.shape[0], 1)) 
print(X) 
print(X.ndim, '; ', X.shape) 
print(y) 
print(y.ndim, '; ', y.shape)

[[10 22 13]
 [ 9  6  5]
 [ 8 12  4]
 [ 6  5  7]]
2 ;  (4, 3)
[[1]
 [0]
 [1]
 [0]]
2 ;  (4, 1)


**Các phép toán với tensor hạng cao**

In [ ]:
m=2 
n=2 
k=3 
T = np.random.randint(low=-5,  
high=5,size=m*n*k).reshape(k,m,n) 
print(T)

[[[ 0  0]
  [ 1  3]]

 [[-3 -1]
  [-2 -2]]

 [[-2  2]
  [-3  3]]]


In [ ]:
m=2 
n=2 
k=3 
t1 = np.random.randint(low=-5,  
high=5,size=m*n*k).reshape(k,m,n) 
t2 = np.random.randint(low=-5,  
high=5,size=m*n*k).reshape(k,m,n) 
t3 = np.random.randint(low=-5,  
high=5,size=m*n*k).reshape(k,m,n) 
t4 = np.random.randint(low=-5,  
high=5,size=m*n*k).reshape(k,m,n)

T = np.stack((t1, t2, t3, t4), axis=-1) 
print(T.shape) 
x = T[:,:,:,0] 
print(x.shape) 
m1 = x[0,:,:] 
print(m1) 
print(m1.shape)

(3, 2, 2, 4)
(3, 2, 2)
[[ 4  1]
 [ 2 -5]]
(2, 2)
